### PR TITLE
Match facebook.com/messages/t as well

### PR DESCRIPTION
**Pull request by lourot**

### CODE REVIEW

**Comment by ppartarr** [comment]
Great addition to the extension, thanks!

**Comment by lourot** [comment]
@ppartarr Thank you for the quick merge :) Will you release this new version in the webstore soon?

**Comment by ppartarr** [comment]
@AurelienLourot Just published version 0.4

**Comment by lourot** [comment]
Thank you! By the way I have been trying to get your theme approved on [Slack](https://slack.draculatheme.com/) but I haven't managed to reach anyone so far.

**Pull request merged**
